### ISSUE TITLE
Error on `npm run dev`

### ISSUE THREAD

**Issue by Donnie** [salttechno/tailwindcss-boilerplate#1]
I cloned the project to my local directory, run `npm install` and `npm run dev` to see this error.
I am looking into solutions, any help would be greatly appreciated!

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle tailwindcss-boilerplate@1.0.0~predev: tailwindcss-boilerplate@1.0.0
6 info lifecycle tailwindcss-boilerplate@1.0.0~dev: tailwindcss-boilerplate@1.0.0
7 verbose lifecycle tailwindcss-boilerplate@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle tailwindcss-boilerplate@1.0.0~dev: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/donnie/go/src/github.com/Donnie/resume/node_modules/.bin:/home/donnie/.local/bin:/home/donnie/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/home/donnie/go/bin:/usr/local/go/bin:/home/donnie/go/bin
9 verbose lifecycle tailwindcss-boilerplate@1.0.0~dev: CWD: /home/donnie/go/src/github.com/Donnie/resume
10 silly lifecycle tailwindcss-boilerplate@1.0.0~dev: Args: [ '-c', 'gulp' ]
11 silly lifecycle tailwindcss-boilerplate@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle tailwindcss-boilerplate@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: tailwindcss-boilerplate@1.0.0 dev: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid tailwindcss-boilerplate@1.0.0
15 verbose cwd /home/donnie/go/src/github.com/Donnie/resume
16 verbose Linux 5.8.0-44-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error tailwindcss-boilerplate@1.0.0 dev: `gulp`
22 error Exit status 1
23 error Failed at the tailwindcss-boilerplate@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
```
npm version
{ 'tailwindcss-boilerplate': '1.0.0',
  npm: '6.14.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '36.1',
  http_parser: '2.9.3',
  icu: '66.1',
  modules: '64',
  napi: '5',
  nghttp2: '1.40.0',
  node: '10.19.0',
  openssl: '1.1.1d',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.34.2',
  v8: '6.8.275.32-node.55',
  zlib: '1.2.11' }
```

**Comment by salttechno** [comment]
Hello,

I have not tried it with Node version 10. But as per [TailwindCSS documentation](https://tailwindcss.com/docs/installation), to use Tailwind CSS with PostCSS, Tailwind CSS requires Node.js 12.13.0 or higher.

Can you please try with Node.js version 12.13.0 or higher? Let me know if the issue persists after using upgraded Node.js.


Thanks.
